<?php
/**
 * Canonical registration select catalogues.
 *
 * @package AdamMembership\Core
 */

declare(strict_types=1);

namespace AdamMembership\Core;

/**
 * Supplies standardized profession sectors and ISO 3166-1 country names.
 */
final class RegistrationFieldCatalog {
	/**
	 * Get the alphabetized professional-sector options.
	 */
	public static function profession_sector_options(): string {
		return implode(
			"\n",
			array(
				'Agricultura / Florestas / Pesca',
				'Arquitetura / Design / Decoração',
				'Artes / Entretenimento / Media',
				'Banca / Seguros / Serviços Financeiros',
				'Beleza / Moda / Bem Estar',
				'Call Center / Help Desk / Suporte',
				'Comercial / Vendas / Ótica',
				'Comunicação Social / Media',
				'Conservação / Manutenção / Técnica',
				'Construção Civil / Construção',
				'Contabilidade / Finanças',
				'Desporto / Ginásios',
				'Direito / Justiça',
				'Educação / Formação',
				'Engenharia (Ambiente / Geologia)',
				'Engenharia (Civil / Topografia)',
				'Engenharia (Eletrotécnica / Eletrónica)',
				'Engenharia (Mecânica / Optotecnia)',
				'Engenharia (Química / Biologia)',
				'Farmácia / Biotecnologia',
				'Forças de Segurança / GNR',
				'Forças de Segurança / Outro',
				'Forças de Segurança / PSP',
				'Gestão de Empresas / Economia',
				'Gestão RH',
				'Hotelaria / Turismo',
				'Imobiliário',
				'Indústria / Produção',
				'Informática (Análise de Sistemas)',
				'Informática (Comercial / Gestão de Conta)',
				'Informática (Formação)',
				'Informática (Gestão de Redes)',
				'Informática (Internet)',
				'Informática (Multimédia)',
				'Informática (Programação)',
				'Informática (Técnico de Hardware)',
				'Limpezas / Domésticas',
				'Lojas / Comércio / Balcão',
				'Militar',
				'Publicidade / Marketing',
				'Relações Públicas / Protocolo',
				'Restauração / Bares / Pastelarias',
				'Saúde / Medicina / Enfermagem',
				'Secretariado / Administrativo',
				'Serviços Sociais / Apoio',
				'Serviços Técnicos',
				'Telecomunicações',
				'Transportes / Logística',
			)
		);
	}

	/**
	 * Get all ISO 3166-1 countries and territories in alphabetized PT-PT.
	 */
	public static function nationality_country_options(): string {
		return implode(
			"\n",
			array(
				'Afeganistão',
				'África do Sul',
				'Alanda',
				'Albânia',
				'Alemanha',
				'Andorra',
				'Angola',
				'Anguila',
				'Antártida',
				'Antígua e Barbuda',
				'Arábia Saudita',
				'Argélia',
				'Argentina',
				'Arménia',
				'Aruba',
				'Austrália',
				'Áustria',
				'Azerbaijão',
				'Baamas',
				'Bangladeche',
				'Barbados',
				'Barém',
				'Bélgica',
				'Belize',
				'Benim',
				'Bermudas',
				'Bielorrússia',
				'Bolívia',
				'Bósnia e Herzegovina',
				'Botsuana',
				'Brasil',
				'Brunei',
				'Bulgária',
				'Burquina Faso',
				'Burundi',
				'Butão',
				'Cabo Verde',
				'Camarões',
				'Camboja',
				'Canadá',
				'Catar',
				'Cazaquistão',
				'Chade',
				'Chéquia',
				'Chile',
				'China',
				'Chipre',
				'Cidade do Vaticano',
				'Colômbia',
				'Comores',
				'Congo-Brazzaville',
				'Congo-Kinshasa',
				'Coreia do Norte',
				'Coreia do Sul',
				'Costa Rica',
				'Côte d’Ivoire (Costa do Marfim)',
				'Croácia',
				'Cuba',
				'Curaçau',
				'Dinamarca',
				'Domínica',
				'Egito',
				'Emirados Árabes Unidos',
				'Equador',
				'Eritreia',
				'Eslováquia',
				'Eslovénia',
				'Espanha',
				'Essuatíni',
				'Estados Unidos',
				'Estónia',
				'Etiópia',
				'Fiji',
				'Filipinas',
				'Finlândia',
				'França',
				'Gabão',
				'Gâmbia',
				'Gana',
				'Geórgia',
				'Gibraltar',
				'Granada',
				'Grécia',
				'Gronelândia',
				'Guadalupe',
				'Guame',
				'Guatemala',
				'Guernesey',
				'Guiana',
				'Guiana Francesa',
				'Guiné',
				'Guiné Equatorial',
				'Guiné-Bissau',
				'Haiti',
				'Honduras',
				'Hong Kong, RAE da China',
				'Hungria',
				'Iémen',
				'Ilha Bouvet',
				'Ilha de Man',
				'Ilha do Natal',
				'Ilha Norfolk',
				'Ilhas Caimão',
				'Ilhas Cook',
				'Ilhas dos Cocos (Keeling)',
				'Ilhas Falkland',
				'Ilhas Faroé',
				'Ilhas Geórgia do Sul e Sandwich do Sul',
				'Ilhas Heard e McDonald',
				'Ilhas Marianas do Norte',
				'Ilhas Marshall',
				'Ilhas Menores Afastadas dos EUA',
				'Ilhas Pitcairn',
				'Ilhas Salomão',
				'Ilhas Turcas e Caicos',
				'Ilhas Virgens Britânicas',
				'Ilhas Virgens dos EUA',
				'Índia',
				'Indonésia',
				'Irão',
				'Iraque',
				'Irlanda',
				'Islândia',
				'Israel',
				'Itália',
				'Jamaica',
				'Japão',
				'Jersey',
				'Jibuti',
				'Jordânia',
				'Koweit',
				'Laos',
				'Lesoto',
				'Letónia',
				'Líbano',
				'Libéria',
				'Líbia',
				'Listenstaine',
				'Lituânia',
				'Luxemburgo',
				'Macau, RAE da China',
				'Macedónia do Norte',
				'Madagáscar',
				'Maiote',
				'Malásia',
				'Maláui',
				'Maldivas',
				'Mali',
				'Malta',
				'Marrocos',
				'Martinica',
				'Maurícia',
				'Mauritânia',
				'México',
				'Mianmar (Birmânia)',
				'Micronésia',
				'Moçambique',
				'Moldávia',
				'Mónaco',
				'Mongólia',
				'Monserrate',
				'Montenegro',
				'Namíbia',
				'Nauru',
				'Nepal',
				'Nicarágua',
				'Níger',
				'Nigéria',
				'Niuê',
				'Noruega',
				'Nova Caledónia',
				'Nova Zelândia',
				'Omã',
				'Países Baixos',
				'Países Baixos Caribenhos',
				'Palau',
				'Panamá',
				'Papua-Nova Guiné',
				'Paquistão',
				'Paraguai',
				'Peru',
				'Polinésia Francesa',
				'Polónia',
				'Porto Rico',
				'Portugal',
				'Quénia',
				'Quirguistão',
				'Quiribáti',
				'Reino Unido',
				'República Centro-Africana',
				'República Dominicana',
				'Reunião',
				'Roménia',
				'Ruanda',
				'Rússia',
				'Salvador',
				'Samoa',
				'Samoa Americana',
				'Santa Helena',
				'Santa Lúcia',
				'São Bartolomeu',
				'São Cristóvão e Neves',
				'São Marinho',
				'São Martinho (Saint-Martin)',
				'São Martinho (Sint Maarten)',
				'São Pedro e Miquelão',
				'São Tomé e Príncipe',
				'São Vicente e Granadinas',
				'Sara Ocidental',
				'Seicheles',
				'Senegal',
				'Serra Leoa',
				'Sérvia',
				'Singapura',
				'Síria',
				'Somália',
				'Sri Lanca',
				'Sudão',
				'Sudão do Sul',
				'Suécia',
				'Suíça',
				'Suriname',
				'Svalbard e Jan Mayen',
				'Tailândia',
				'Taiwan',
				'Tajiquistão',
				'Tanzânia',
				'Território Britânico do Oceano Índico',
				'Territórios Austrais Franceses',
				'Territórios palestinianos',
				'Timor-Leste',
				'Togo',
				'Tonga',
				'Toquelau',
				'Trindade e Tobago',
				'Tunísia',
				'Turquemenistão',
				'Turquia',
				'Tuvalu',
				'Ucrânia',
				'Uganda',
				'Uruguai',
				'Usbequistão',
				'Vanuatu',
				'Venezuela',
				'Vietname',
				'Wallis e Futuna',
				'Zâmbia',
				'Zimbabué',
			)
		);
	}
}
